spring.datasource.url=jdbc:mariadb://175.120.35.228:3306/agent_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=root

# CSV Import 설정
app.csv.base-dir=./data
app.csv.encoding=UTF-8
app.loader.create-id=true
app.loader.truncate=false
app.import.on-start=true
